// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffing.proto

package com.project;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:project.Empty)
    com.google.protobuf.MessageOrBuilder {
}
