// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffing.proto

package com.project;

public final class StaffingImpl {
  private StaffingImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_project_TimeLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_project_TimeLevel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_project_APIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_project_APIResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_project_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_project_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016staffing.proto\022\007project\"(\n\tTimeLevel\022\014" +
      "\n\004time\030\001 \001(\t\022\r\n\005level\030\002 \001(\t\"Z\n\013APIRespon" +
      "se\022\024\n\014responseText\030\001 \001(\t\022\024\n\014responseCode" +
      "\030\002 \001(\005\022\017\n\007doctors\030\003 \001(\t\022\016\n\006nurses\030\004 \001(\t\"" +
      "\007\n\005Empty2G\n\010Staffing\022;\n\rstaffRequired\022\022." +
      "project.TimeLevel\032\024.project.APIResponse\"" +
      "\000B\035\n\013com.projectB\014StaffingImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_project_TimeLevel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_project_TimeLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_project_TimeLevel_descriptor,
        new java.lang.String[] { "Time", "Level", });
    internal_static_project_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_project_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_project_APIResponse_descriptor,
        new java.lang.String[] { "ResponseText", "ResponseCode", "Doctors", "Nurses", });
    internal_static_project_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_project_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_project_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
