// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staffing.proto

package com.project;

public interface TimeLevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:project.TimeLevel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string time = 1;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string level = 2;</code>
   */
  java.lang.String getLevel();
  /**
   * <code>string level = 2;</code>
   */
  com.google.protobuf.ByteString
      getLevelBytes();
}
